In [ ]:
# data_prova.py
from syscore.dateutils import Frequency
from sysobjects.contracts import futuresContract
from sysbrokers.IB.ib_futures_contract_price_data import ibFuturesContractPriceData,ibFuturesContractData
from sysdata.data_blob import dataBlob


from sysbrokers.IB.ib_connection import connectionIB
from sysbrokers.IB.ib_instruments_data import ibFuturesInstrumentData
from sysbrokers.IB.ib_futures_contracts_data import ibFuturesContractData
from sysproduction.data.broker import dataBroker

from ib_insync import util
util.startLoop() #only required when running inside a notebook

Configuring sim logging

In [ ]:
conn = connectionIB(999) # the first compulsory value is the client_id; the keyword args are the default values and can be omitted
data = dataBlob()
databroker = dataBroker(data)
# data.add_class_object(ibFuturesInstrumentData)
# data.add_class_object(ibFuturesContractData)

2025-03-16 18:08:34 DEBUG root {'component': 'mongoIbBrokerClientIdData'} Locked IB client ID 122

2025-03-16 18:11:50 DEBUG ibFuturesContractPriceData Reqid -1: 2108 Market data farm connection is inactive but should be available upon demand.usfarm.nj for None
2025-03-16 18:11:50 DEBUG ibFuturesContractPriceData Reqid -1: 2108 Market data farm connection is inactive but should be available upon demand.usfarm.nj for None
2025-03-16 18:25:42 ERROR ib_insync.wrapper Error 200, reqId 7: No security definition has been found for the request, contract: Future(symbol='3KTB', lastTradeDateOrContractMonth='20250616', multiplier='1000000', exchange='KSE')
2025-03-16 18:25:42 WARNING ibFuturesContractPriceData Reqid 7: 200 No security definition has been found for the request for Future(symbol='3KTB', lastTradeDateOrContractMonth='20250616', multiplier='1000000', exchange='KSE')
2025-03-16 18:25:42 WARNING ibFuturesContractData Reqid 7: 200 No security definition has been found for the request for Future(symbol='3KTB', lastTradeDateOrContractMonth='20250616', multiplier='1000000', exchange='KSE')
2025-03-16 18:26:25 ERROR ib_insync.wrapper Error 200, reqId 11: No security definition has been found for the request, contract: Future(symbol='3KTB', lastTradeDateOrContractMonth='20250317', multiplier='1000000', exchange='KSE')
2025-03-16 18:26:25 WARNING ibFuturesContractPriceData Reqid 11: 200 No security definition has been found for the request for Future(symbol='3KTB', lastTradeDateOrContractMonth='20250317', multiplier='1000000', exchange='KSE')
2025-03-16 18:26:25 WARNING ibFuturesContractData Reqid 11: 200 No security definition has been found for the request for Future(symbol='3KTB', lastTradeDateOrContractMonth='20250317', multiplier='1000000', exchange='KSE')
2025-03-16 18:26:25 WARNING ibFuturesContractData Reqid 11: 200 No security definition has been found for the request for Future(symbol='3KTB', lastTradeDateOrContractMonth='20250317', multiplier='1000000', exchange='KSE')
2025-03-16 18:31:33 DEBUG ibFuturesContractPriceData Reqid -1: 2104 Market data farm connection is OK:usfarm.nj for None
2025-03-16 18:31:33 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:usfarm.nj for None
2025-03-16 18:31:33 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:usfarm.nj for None
2025-03-16 18:31:33 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2104 Market data farm connection is OK:usfarm.nj for None
2025-03-16 18:32:08 DEBUG ibFuturesContractPriceData Reqid -1: 2104 Market data farm connection is OK:jfarm for None
2025-03-16 18:32:08 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:jfarm for None
2025-03-16 18:32:08 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:jfarm for None
2025-03-16 18:32:08 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2104 Market data farm connection is OK:jfarm for None
2025-03-16 18:32:17 DEBUG ibFuturesContractPriceData Reqid -1: 2106 HMDS data farm connection is OK:apachmds for None
2025-03-16 18:32:17 DEBUG ibFuturesContractData Reqid -1: 2106 HMDS data farm connection is OK:apachmds for None
2025-03-16 18:32:17 DEBUG ibFuturesContractData Reqid -1: 2106 HMDS data farm connection is OK:apachmds for None
2025-03-16 18:32:17 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2106 HMDS data farm connection is OK:apachmds for None
2025-03-16 18:33:54 DEBUG ibFuturesContractPriceData Reqid -1: 2108 Market data farm connection is inactive but should be available upon demand.usfarm.nj for None
2025-03-16 18:33:54 DEBUG ibFuturesContractData Reqid -1: 2108 Market data farm connection is inactive but should be available upon demand.usfarm.nj for None
2025-03-16 18:33:54 DEBUG ibFuturesContractData Reqid -1: 2108 Market data farm connection is inactive but should be available upon demand.usfarm.nj for None
2025-03-16 18:33:54 DEBUG ibFuturesContractData Reqid -1: 2108 Market data farm connection is inactive but should be available upon demand.usfarm.nj for None
2025-03-16 18:33:54 DEBUG ibFuturesContractPriceData Reqid -1: 2108 Market data farm connection is inactive but should be available upon demand.usfarm.nj for None
2025-03-16 18:33:54 DEBUG ibFuturesContractData Reqid -1: 2108 Market data farm connection is inactive but should be available upon demand.usfarm.nj for None
2025-03-16 18:33:54 DEBUG ibFuturesContractData Reqid -1: 2108 Market data farm connection is inactive but should be available upon demand.usfarm.nj for None
2025-03-16 18:33:54 DEBUG ibFuturesContractData Reqid -1: 2108 Market data farm connection is inactive but should be available upon demand.usfarm.nj for None
2025-03-16 18:33:54 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2108 Market data farm connection is inactive but should be available upon demand.usfarm.nj for None
2025-03-16 18:33:54 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2108 Market data farm connection is inactive but should be available upon demand.usfarm.nj for None
2025-03-16 19:30:26 DEBUG ibFuturesContractPriceData Reqid -1: 2103 Market data farm connection is broken:jfarm for None
2025-03-16 19:30:26 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:jfarm for None
2025-03-16 19:30:26 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:jfarm for None
2025-03-16 19:30:26 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:jfarm for None
2025-03-16 19:30:26 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2103 Market data farm connection is broken:jfarm for None
2025-03-16 19:30:28 DEBUG ibFuturesContractPriceData Reqid -1: 2104 Market data farm connection is OK:jfarm for None
2025-03-16 19:30:28 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:jfarm for None
2025-03-16 19:30:28 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:jfarm for None
2025-03-16 19:30:28 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:jfarm for None
2025-03-16 19:30:28 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2104 Market data farm connection is OK:jfarm for None
2025-03-16 20:53:55 DEBUG ibFuturesContractPriceData Reqid -1: 2103 Market data farm connection is broken:eufarm for None
2025-03-16 20:53:55 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:eufarm for None
2025-03-16 20:53:55 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:eufarm for None
2025-03-16 20:53:55 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:eufarm for None
2025-03-16 20:53:55 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2103 Market data farm connection is broken:eufarm for None
2025-03-16 20:53:55 DEBUG ibFuturesContractPriceData Reqid -1: 2105 HMDS data farm connection is broken:euhmds for None
2025-03-16 20:53:55 DEBUG ibFuturesContractData Reqid -1: 2105 HMDS data farm connection is broken:euhmds for None
2025-03-16 20:53:55 DEBUG ibFuturesContractData Reqid -1: 2105 HMDS data farm connection is broken:euhmds for None
2025-03-16 20:53:55 DEBUG ibFuturesContractData Reqid -1: 2105 HMDS data farm connection is broken:euhmds for None
2025-03-16 20:53:55 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2105 HMDS data farm connection is broken:euhmds for None
2025-03-16 20:53:55 DEBUG ibFuturesContractPriceData Reqid -1: 2103 Market data farm connection is broken:eufarmnj for None
2025-03-16 20:53:55 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:eufarmnj for None
2025-03-16 20:53:55 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:eufarmnj for None
2025-03-16 20:53:55 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:eufarmnj for None
2025-03-16 20:53:55 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2103 Market data farm connection is broken:eufarmnj for None
2025-03-16 20:53:55 DEBUG ibFuturesContractPriceData Reqid -1: 2103 Market data farm connection is broken:cashfarm for None
2025-03-16 20:53:55 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:cashfarm for None
2025-03-16 20:53:55 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:cashfarm for None
2025-03-16 20:53:55 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:cashfarm for None
2025-03-16 20:53:55 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2103 Market data farm connection is broken:cashfarm for None
2025-03-16 20:53:55 DEBUG ibFuturesContractPriceData Reqid -1: 2103 Market data farm connection is broken:usfarm for None
2025-03-16 20:53:55 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:usfarm for None
2025-03-16 20:53:55 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:usfarm for None
2025-03-16 20:53:55 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:usfarm for None
2025-03-16 20:53:55 DEBUG ibFuturesContractPriceData Reqid -1: 2105 HMDS data farm connection is broken:ushmds for None
2025-03-16 20:53:55 DEBUG ibFuturesContractData Reqid -1: 2105 HMDS data farm connection is broken:ushmds for None
2025-03-16 20:53:55 DEBUG ibFuturesContractData Reqid -1: 2105 HMDS data farm connection is broken:ushmds for None
2025-03-16 20:53:55 DEBUG ibFuturesContractData Reqid -1: 2105 HMDS data farm connection is broken:ushmds for None
2025-03-16 20:53:55 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2103 Market data farm connection is broken:usfarm for None
2025-03-16 20:53:55 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2105 HMDS data farm connection is broken:ushmds for None
2025-03-16 20:53:55 DEBUG ibFuturesContractPriceData Reqid -1: 2103 Market data farm connection is broken:usopt for None
2025-03-16 20:53:55 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:usopt for None
2025-03-16 20:53:55 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:usopt for None
2025-03-16 20:53:55 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:usopt for None
2025-03-16 20:53:55 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2103 Market data farm connection is broken:usopt for None
2025-03-16 20:53:56 DEBUG ibFuturesContractPriceData Reqid -1: 2103 Market data farm connection is broken:usfuture for None
2025-03-16 20:53:56 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:usfuture for None
2025-03-16 20:53:56 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:usfuture for None
2025-03-16 20:53:56 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:usfuture for None
2025-03-16 20:53:56 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2103 Market data farm connection is broken:usfuture for None
2025-03-16 20:53:56 DEBUG ibFuturesContractPriceData Reqid -1: 2105 HMDS data farm connection is broken:apachmds for None
2025-03-16 20:53:56 DEBUG ibFuturesContractData Reqid -1: 2105 HMDS data farm connection is broken:apachmds for None
2025-03-16 20:53:56 DEBUG ibFuturesContractData Reqid -1: 2105 HMDS data farm connection is broken:apachmds for None
2025-03-16 20:53:56 DEBUG ibFuturesContractData Reqid -1: 2105 HMDS data farm connection is broken:apachmds for None
2025-03-16 20:53:56 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2105 HMDS data farm connection is broken:apachmds for None
2025-03-16 20:53:56 DEBUG ibFuturesContractPriceData Reqid -1: 2103 Market data farm connection is broken:jfarm for None
2025-03-16 20:53:56 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:jfarm for None
2025-03-16 20:53:56 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:jfarm for None
2025-03-16 20:53:56 DEBUG ibFuturesContractData Reqid -1: 2103 Market data farm connection is broken:jfarm for None
2025-03-16 20:53:56 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2103 Market data farm connection is broken:jfarm for None
2025-03-16 20:53:56 DEBUG ibFuturesContractPriceData Reqid -1: 2106 HMDS data farm connection is OK:euhmds for None
2025-03-16 20:53:56 DEBUG ibFuturesContractData Reqid -1: 2106 HMDS data farm connection is OK:euhmds for None
2025-03-16 20:53:56 DEBUG ibFuturesContractData Reqid -1: 2106 HMDS data farm connection is OK:euhmds for None
2025-03-16 20:53:56 DEBUG ibFuturesContractData Reqid -1: 2106 HMDS data farm connection is OK:euhmds for None
2025-03-16 20:53:56 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2106 HMDS data farm connection is OK:euhmds for None
2025-03-16 20:53:56 DEBUG ibFuturesContractPriceData Reqid -1: 2104 Market data farm connection is OK:cashfarm for None
2025-03-16 20:53:56 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:cashfarm for None
2025-03-16 20:53:56 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:cashfarm for None
2025-03-16 20:53:56 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:cashfarm for None
2025-03-16 20:53:56 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2104 Market data farm connection is OK:cashfarm for None
2025-03-16 20:53:56 DEBUG ibFuturesContractPriceData Reqid -1: 2106 HMDS data farm connection is OK:ushmds for None
2025-03-16 20:53:56 DEBUG ibFuturesContractData Reqid -1: 2106 HMDS data farm connection is OK:ushmds for None
2025-03-16 20:53:56 DEBUG ibFuturesContractData Reqid -1: 2106 HMDS data farm connection is OK:ushmds for None
2025-03-16 20:53:57 DEBUG ibFuturesContractData Reqid -1: 2106 HMDS data farm connection is OK:ushmds for None
2025-03-16 20:53:57 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2106 HMDS data farm connection is OK:ushmds for None
2025-03-16 20:53:57 DEBUG ibFuturesContractPriceData Reqid -1: 2104 Market data farm connection is OK:eufarmnj for None
2025-03-16 20:53:57 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:eufarmnj for None
2025-03-16 20:53:57 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:eufarmnj for None
2025-03-16 20:53:57 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:eufarmnj for None
2025-03-16 20:53:57 DEBUG ibFuturesContractPriceData Reqid -1: 2104 Market data farm connection is OK:eufarm for None
2025-03-16 20:53:57 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:eufarm for None
2025-03-16 20:53:57 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:eufarm for None
2025-03-16 20:53:57 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:eufarm for None
2025-03-16 20:53:57 DEBUG ibFuturesContractPriceData Reqid -1: 2104 Market data farm connection is OK:usopt for None
2025-03-16 20:53:57 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:usopt for None
2025-03-16 20:53:57 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:usopt for None
2025-03-16 20:53:57 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:usopt for None
2025-03-16 20:53:57 DEBUG ibFuturesContractPriceData Reqid -1: 2104 Market data farm connection is OK:usfarm for None
2025-03-16 20:53:57 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:usfarm for None
2025-03-16 20:53:57 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:usfarm for None
2025-03-16 20:53:57 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:usfarm for None
2025-03-16 20:53:57 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2104 Market data farm connection is OK:eufarmnj for None
2025-03-16 20:53:57 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2104 Market data farm connection is OK:eufarm for None
2025-03-16 20:53:57 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2104 Market data farm connection is OK:usopt for None
2025-03-16 20:53:57 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2104 Market data farm connection is OK:usfarm for None
2025-03-16 20:53:57 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2104 Market data farm connection is OK:usfuture for None
2025-03-16 20:53:57 DEBUG ibFuturesContractPriceData Reqid -1: 2104 Market data farm connection is OK:usfuture for None
2025-03-16 20:53:57 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:usfuture for None
2025-03-16 20:53:57 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:usfuture for None
2025-03-16 20:53:57 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:usfuture for None
2025-03-16 20:53:58 DEBUG ibFuturesContractPriceData Reqid -1: 2106 HMDS data farm connection is OK:apachmds for None
2025-03-16 20:53:58 DEBUG ibFuturesContractData Reqid -1: 2106 HMDS data farm connection is OK:apachmds for None
2025-03-16 20:53:58 DEBUG ibFuturesContractData Reqid -1: 2106 HMDS data farm connection is OK:apachmds for None
2025-03-16 20:53:58 DEBUG ibFuturesContractData Reqid -1: 2106 HMDS data farm connection is OK:apachmds for None
2025-03-16 20:53:58 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2106 HMDS data farm connection is OK:apachmds for None
2025-03-16 20:53:58 DEBUG ibFuturesContractPriceData Reqid -1: 2104 Market data farm connection is OK:jfarm for None
2025-03-16 20:53:58 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:jfarm for None
2025-03-16 20:53:58 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:jfarm for None
2025-03-16 20:53:58 DEBUG ibFuturesContractData Reqid -1: 2104 Market data farm connection is OK:jfarm for None
2025-03-16 20:53:58 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2104 Market data farm connection is OK:jfarm for None
2025-03-16 21:30:02 DEBUG ibFuturesContractPriceData Reqid -1: 2105 HMDS data farm connection is broken:apachmds for None
2025-03-16 21:30:02 DEBUG ibFuturesContractData Reqid -1: 2105 HMDS data farm connection is broken:apachmds for None
2025-03-16 21:30:02 DEBUG ibFuturesContractData Reqid -1: 2105 HMDS data farm connection is broken:apachmds for None
2025-03-16 21:30:02 DEBUG ibFuturesContractData Reqid -1: 2105 HMDS data farm connection is broken:apachmds for None
2025-03-16 21:30:02 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2105 HMDS data farm connection is broken:apachmds for None
2025-03-16 21:30:04 DEBUG ibFuturesContractPriceData Reqid -1: 2106 HMDS data farm connection is OK:apachmds for None
2025-03-16 21:30:04 DEBUG ibFuturesContractData Reqid -1: 2106 HMDS data farm connection is OK:apachmds for None
2025-03-16 21:30:04 DEBUG ibFuturesContractData Reqid -1: 2106 HMDS data farm connection is OK:apachmds for None
2025-03-16 21:30:04 DEBUG ibFuturesContractData Reqid -1: 2106 HMDS data farm connection is OK:apachmds for None
2025-03-16 21:30:04 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2106 HMDS data farm connection is OK:apachmds for None
2025-03-16 21:30:47 DEBUG ibFuturesContractPriceData Reqid -1: 2105 HMDS data farm connection is broken:apachmds for None
2025-03-16 21:30:47 DEBUG ibFuturesContractData Reqid -1: 2105 HMDS data farm connection is broken:apachmds for None
2025-03-16 21:30:47 DEBUG ibFuturesContractData Reqid -1: 2105 HMDS data farm connection is broken:apachmds for None
2025-03-16 21:30:47 DEBUG ibFuturesContractData Reqid -1: 2105 HMDS data farm connection is broken:apachmds for None

In [4]:
ibfuturesdata = ibFuturesContractPriceData(conn, data=data)
a=ibfuturesdata.get_list_of_instrument_codes_with_merged_price_data() # returns list of instruments defined in [futures config file](/sysbrokers/IB/ibConfigFutures.csv)

In [18]:
ibfuturesdata.contract_dates_with_merged_price_data_for_instrument_code("KR3")
# contract = futuresContract("KR3","20250617")
# ib_futures_contract_data = ibFuturesContractData(conn, data=data)
# ib_futures_contract_data.get_contract_object_with_IB_data(contract)

['20230321',
 '20230620',
 '20230919',
 '20231219',
 '20240319',
 '20240618',
 '20240913',
 '20241217',
 '20250317',
 '20250616']

In [3]:
ibfuturesdata = ibFuturesContractPriceData(conn, data=data)
a=ibfuturesdata.get_list_of_instrument_codes_with_merged_price_data() # returns list of instruments defined in [futures config file](/sysbrokers/IB/ibConfigFutures.csv)
b=ibfuturesdata.contract_dates_with_merged_price_data_for_instrument_code("SP500_micro") # returns list of contract dates
c=ibfuturesdata.get_prices_at_frequency_for_contract_object(futuresContract("SP500_micro", "202503"), frequency=Frequency.Day) # returns daily price and volume data
c.head()
# expiry_date = "202503"
# contract_name = "SP500_micro"
# dates = databroker.get_list_of_contract_dates_for_instrument_code(contract_name, allow_expired=True)

# contract = futuresContract(contract_name, expiry_date)
# a = databroker.get_list_of_instrument_codes_with_merged_price_data()
# a = databroker.get_prices_at_frequency_for_contract_object(
#     contract_object=contract,
#     frequency=Frequency.Day
#     )
# b = databroker.get_prices_at_frequency_for_potentially_expired_contract_object(
#     contract_object=contract,
#     frequency=Frequency.Day
#     )

2025-02-25 23:19:49 DEBUG ibFuturesContractPriceData {'instrument_code': 'SP500_micro', 'contract_date': '20250300'} Updating log attributes
2025-02-25 23:19:50 DEBUG ibFuturesContractPriceData Log attributes reset

                        OPEN     HIGH      LOW    FINAL  VOLUME
index
2024-02-27 23:00:00  5305.50  5305.50  5305.50  5305.50     0.0
2024-02-28 23:00:00  5295.50  5295.50  5295.50  5295.50     0.0
2024-02-29 23:00:00  5318.75  5318.75  5318.75  5318.75     0.0
2024-03-01 23:00:00  5340.00  5360.00  5339.00  5360.00    14.0
2024-03-04 23:00:00  5365.00  5365.00  5347.50  5355.25     2.0

In [ ]:
from sysdata.sim.csv_futures_sim_data import csvFuturesSimData
data=csvFuturesSimData()
data

Prova per utilizzare i dati dal db

In [26]:
from sysdata.config.configdata import Config
from systems.provided.futures_chapter15.estimatedsystem import futures_system
from sysdata.sim.db_futures_sim_data import dbFuturesSimData
from sysdata.sim.csv_futures_sim_data import csvFuturesSimData
from ib_insync import util

util.startLoop() #only required when running inside a notebook
my_config=Config("private.001_demo.config.yaml")
my_data = dbFuturesSimData()
my_csv_data = csvFuturesSimData()
system = futures_system(config=my_config, data=my_data)

2025-03-25 16:15:43 DEBUG config {'type': 'config', 'stage': 'config'} Adding config defaults

In [22]:
my_config.csv_roll_calendar_directory

'private.futures.roll_calendars_csv'

In [27]:
system.data.get_instrument_list()

['EURCHF',
 'DOW_mini',
 'GASOIL',
 'MSCISING',
 'US2',
 'US-UTILS',
 'GBP',
 'GOLD',
 'GICS',
 'EUROSTX-SMALL',
 'SUGAR11',
 'TOPIX',
 'EU-BANKS',
 'GAS-PEN',
 'US-MATERIAL',
 'CNH-onshore',
 'COCOA_LDN',
 'KOSDAQ',
 'BRENT-LAST',
 'EPRA-EUROPE',
 'CHF',
 'CAD2',
 'EU-DIV30',
 'EU-DJ-TECH',
 'STEEL',
 'FANG',
 'JGB',
 'SARONA',
 'BITCOIN',
 'GILT',
 'EU-CONSTRUCTION',
 'SUGAR16',
 'NIKKEI400',
 'EU-FOOD',
 'US-INDUSTRY',
 'FTSECHINAA',
 'CZK',
 'IRS',
 'HIGHYIELD',
 'MXP',
 'BRE',
 'SGD',
 'KRWUSD_mini',
 'GASOILINE_micro',
 'DJSTX-SMALL',
 'MSCIWORLD',
 'EU-REALESTATE',
 'KR3',
 'REDWHEAT',
 'OATIES',
 'US30',
 'BUXL',
 'HANGTECH',
 'FTSETAIWAN',
 'FTSECHINAH',
 'SP500',
 'COCOA',
 'RICE',
 'CRUDE_W_mini',
 'US3',
 'JP-REALESTATE',
 'SEK',
 'COAL',
 'SILVER',
 'US-TECH',
 'EU-HEALTH',
 'BRENT_W',
 'EUA',
 'DAX',
 'SGX',
 'OAT',
 'GBPJPY',
 'WHEY',
 'EURO600',
 'HANGENT',
 'EURAUD',
 'CNH',
 'VNKI',
 'LUMBER-new',
 'YENEUR',
 'R1000',
 'CORN',
 'MILK',
 'CHEESE',
 'EUROSTX',
 'RUBBER',
 'PALLAD',
 'GOLD-mini',
 'EURIBOR',
 'MILKDRY',
 'COTTON2',
 'GASOILINE',
 'COAL-GEORDIE',
 'GBP_micro',
 'HANG_mini',
 'V2X',
 'EU-MID',
 'IG',
 'OJ',
 'GAS-LAST',
 'CAD5',
 'WHEAT_ICE',
 'NOK',
 'CORN_mini',
 'GAS_US_mini',
 'BUTTER',
 'US10',
 'ETHANOL',
 'SOFR',
 'US-HEALTH',
 'US5',
 'MILLWHEAT',
 'EU-INSURE',
 'US10U',
 'US-DISCRETE',
 'NASDAQ',
 'IBEX_mini',
 'SMI',
 'SMI-MID',
 'TWD-mini',
 'AUDJPY',
 'US-STAPLES',
 'US-REALESTATE',
 'ALUMINIUM',
 'AEX',
 'SP500_micro',
 'AUD',
 'WHEAT_mini',
 'NICKEL_LME',
 'EUROSTX-LARGE',
 'SPI200',
 'CANOLA',
 'SGD_mini',
 'EURCAD',
 'SOYMEAL',
 'IBEX',
 'FTSE250',
 'HEATOIL-ICE',
 'BBCOMM',
 'ROBUSTA',
 'EU-DJ-UTIL',
 'US-FINANCE',
 'LEAD_LME',
 'EU-OIL',
 'MUMMY',
 'KR10',
 'EU-TECH',
 'DX',
 'MSCIEAFA',
 'MILKWET',
 'GOLD_micro',
 'IRON',
 'DOW',
 'AUD_micro',
 'ETHER-micro',
 'FTSEINDO',
 'JGB-SGX-mini',
 'EUR_mini',
 'CHFJPY',
 'EU-UTILS',
 'JPY',
 'ALUMINIUM_LME',
 'CHF_micro',
 'KOSPI',
 'EU-BASIC',
 'FED',
 'RUR',
 'CAD10',
 'GAS_US',
 'BONO',
 'SWISSLEAD',
 'COFFEE',
 'NASDAQ_micro',
 'BOBL',
 'BOVESPA',
 'VIX',
 'EU-CHEM',
 'FTSE100',
 'JPY_mini',
 'SOYBEAN',
 'SUGAR_WHITE',
 'COPPER',
 'JGB-mini',
 'SOYOIL',
 'COPPER-micro',
 'FEEDCOW',
 'PLN',
 'WHEAT',
 'VIX_mini',
 'COTTON',
 'CRUDE_W',
 'EUROSTX200-LARGE',
 'HANGENT_mini',
 'CAC',
 'COPPER-mini',
 'CRUDE_ICE',
 'SP400',
 'LEANHOG',
 'GBPEUR',
 'ETHEREUM',
 'TWD',
 'BUND',
 'SONIA3',
 'NIKKEI',
 'GASOILINE_ICE',
 'HANG',
 'LIVECOW',
 'CLP',
 'MSCIEMASIA',
 'GBPCHF',
 'NZD',
 'MSCIASIA',
 'OMX',
 'RUSSELL',
 'ZINC_LME',
 'BTP',
 'HOUSE-US',
 'RUSSELL_mini',
 'EU-TRAVEL',
 'BB3M',
 'EU-HOUSE',
 'TIN_LME',
 'US-PROPERTY',
 'FTSEVIET',
 'EU-DJ-OIL',
 'EU-RETAIL',
 'EU-MEDIA',
 'PLAT',
 'BTP3',
 'EU-DJ-TELECOM',
 'INR',
 'EUR_micro',
 'KRWUSD',
 'COPPER_LME',
 'MSCITAIWAN',
 'CAD_micro',
 'KOSPI_mini',
 'EU-AUTO',
 'US-ENERGY',
 'ZAR',
 'US20',
 'SOYBEAN_mini',
 'CRUDE_W_micro',
 'CAD',
 'AEX_mini',
 'HEATOIL',
 'CHINAA-CON',
 'EURIBOR-ICE',
 'CH10',
 'EUR',
 'SHATZ',
 'MIB']

In [28]:
system.data.get_multiple_prices("EURCHF")

,PRICE,FORWARD,CARRY,PRICE_CONTRACT,FORWARD_CONTRACT,CARRY_CONTRACT
index,,,,,,
2024-04-01 23:00:00,0.9610,0.9557,0.9557,20240900,20241200,20241200
2024-04-02 23:00:00,0.9664,0.9609,0.9609,20240900,20241200,20241200
2024-04-03 23:00:00,0.9677,0.9622,0.9622,20240900,20241200,20241200
2024-04-04 23:00:00,0.9689,0.9631,0.9631,20240900,20241200,20241200
2024-04-05 23:00:00,0.9667,0.9609,0.9609,20240900,20241200,20241200
...,...,...,...,...,...,...
2024-12-10 23:00:00,NaN,0.9292,0.9292,20240900,20241200,20241200
2024-12-11 23:00:00,NaN,0.9280,0.9280,20240900,20241200,20241200
2024-12-12 23:00:00,NaN,0.9339,0.9339,20240900,20241200,20241200
2024-12-13 23:00:00,NaN,0.9371,0.9371,20240900,20241200,20241200
2024-12-16 23:00:00,NaN,0.9384,0.9384,20240900,20241200,20241200

In [7]:
a = getattr(my_config, "csv_roll_calendar_directory", True)

In [7]:
from ib_insync import *
from ib_insync import util

util.startLoop() #only required when running inside a notebook

if not ib.isConnected():
	ib.connect('127.0.0.1', 7497, clientId=1)

contract = Future(symbol='ESTX50', lastTradeDateOrContractMonth='202503', exchange='EUREX', currency='EUR')
ib.qualifyContracts(contract)
print(contract)

Unknown contract: Future(symbol='ESTX50', lastTradeDateOrContractMonth='202503', exchange='EUREX', currency='EUR')

Future(symbol='ESTX50', lastTradeDateOrContractMonth='202503', exchange='EUREX', currency='EUR')

In [10]:
from sysdata.config.configdata import Config

config = Config.default_config()
CSV_ROLL_CALENDAR_DIRECTORY = config.get_element_or_default(
    "csv_roll_calendars_directory", "data.futures.roll_calendars_csv"
)
print(
    f"CSV_ROLL_CALENDAR_DIRECTORY from config: {CSV_ROLL_CALENDAR_DIRECTORY}",
)

2025-03-28 13:40:56 DEBUG config {'type': 'config', 'stage': 'config'} Adding config defaults
CSV_ROLL_CALENDAR_DIRECTORY from config: private.futures.roll_calendars_csv

In [8]:
CSV_ROLL_CALENDAR_DIRECTORY = config.get_element_or_default(
    "csv_roll_calendars_directory", "data.futures.roll_calendars_csv"
)
print(
    f"CSV_ROLL_CALENDAR_DIRECTORY from config: {CSV_ROLL_CALENDAR_DIRECTORY}",
)

CSV_ROLL_CALENDAR_DIRECTORY from config: data.futures.roll_calendars_csv

In [ ]:
config.csv