### Initial imports

In [1]:
from sysinit.futures.seed_price_data_from_IB import seed_price_data_from_IB
from sysinit.futures.rollcalendars_from_db_prices_to_csv import build_and_write_roll_calendar
from sysinit.futures.multipleprices_from_db_prices_and_csv_calendars_to_db import (
    process_multiple_prices_single_instrument
)
from sysinit.futures.adjustedprices_from_db_multiple_to_db import process_adjusted_prices_single_instrument
from ib_insync import util
util.startLoop() #only required when running inside a notebook

Configuring sim logging
2025-04-10 22:27:39 DEBUG config {'type': 'config', 'stage': 'config'} Adding config defaults

### Configuration
- define instrument
- define calendar output datapath

In [2]:
instrument_code = 'AEX'
calendar_output_datapath = "/home/nicola/"

### Retrieve data from IB

In [ ]:
seed_price_data_from_IB(instrument_code)

### Build roll calendar

This will build the calendar from the just retrieved prices. Make sure you have correctly set the output datapath in the above section.
After the calendar is generated, merge it with the production calendar. Default is in `~/pysystemtrade/private/futures/roll_calendars_csv`

In [6]:
build_and_write_roll_calendar(instrument_code, output_datapath=calendar_output_datapath)

Writing to /home/nicola/
Prepping roll calendar... might take a few seconds
2018-04-15 00:00:00,20180400,20180500,20180500
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de320>
2018-05-15 00:00:00,20180500,20180600,20180600
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306dde70>
2018-06-15 00:00:00,20180600,20180700,20180700
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddf30>
2018-07-15 00:00:00,20180700,20180800,20180800
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306deb60>
2018-08-15 00:00:00,20180800,20180900,20180900
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de260>
2018-09-15 00:00:00,20180900,20181000,20181000
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306dec20>
2018-10-15 00:00:00,20181000,20181100,20181100
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de0e0>
2018-11-15 00:00:00,20181100,20181200,20181200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de320>
2018-12-15 00:00:00,20181200,20190100,20190100
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306dde70>
2019-01-15 00:00:00,20190100,20190200,20190200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddf30>
2019-02-15 00:00:00,20190200,20190300,20190300
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306deb60>
2019-03-15 00:00:00,20190300,20190400,20190400
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de260>
2019-04-15 00:00:00,20190400,20190500,20190500
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306dec20>
2019-05-15 00:00:00,20190500,20190600,20190600
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de0e0>
2019-06-15 00:00:00,20190600,20190700,20190700
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de320>
2019-07-15 00:00:00,20190700,20190800,20190800
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306dde70>
2019-08-15 00:00:00,20190800,20190900,20190900
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddf30>
2019-09-15 00:00:00,20190900,20191000,20191000
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306deb60>
2019-10-15 00:00:00,20191000,20191100,20191100
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de260>
2019-11-15 00:00:00,20191100,20191200,20191200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306dec20>
2019-12-15 00:00:00,20191200,20200100,20200100
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de0e0>
2020-01-15 00:00:00,20200100,20200200,20200200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de320>
2020-02-15 00:00:00,20200200,20200300,20200300
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306dde70>
2020-03-15 00:00:00,20200300,20200400,20200400
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddf30>
2020-04-15 00:00:00,20200400,20200500,20200500
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306deb60>
2020-05-15 00:00:00,20200500,20200600,20200600
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de260>
2020-06-15 00:00:00,20200600,20200700,20200700
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306dec20>
2020-07-15 00:00:00,20200700,20200800,20200800
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de0e0>
2020-08-15 00:00:00,20200800,20200900,20200900
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de320>
2020-09-15 00:00:00,20200900,20201000,20201000
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306dde70>
2020-10-15 00:00:00,20201000,20201100,20201100
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddf30>
2020-11-15 00:00:00,20201100,20201200,20201200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306deb60>
2020-12-15 00:00:00,20201200,20210100,20210100
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de470>
2021-01-15 00:00:00,20210100,20210200,20210200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de020>
2021-02-15 00:00:00,20210200,20210300,20210300
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de0e0>
2021-03-15 00:00:00,20210300,20210400,20210400
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de320>
2021-04-15 00:00:00,20210400,20210500,20210500
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de2f0>
2021-05-15 00:00:00,20210500,20210600,20210600
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddf30>
2021-06-15 00:00:00,20210600,20210700,20210700
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de230>
2021-07-15 00:00:00,20210700,20210800,20210800
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de470>
2021-08-15 00:00:00,20210800,20210900,20210900
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306dec20>
2021-09-15 00:00:00,20210900,20211000,20211000
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de0e0>
2021-10-15 00:00:00,20211000,20211100,20211100
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306dece0>
2021-11-15 00:00:00,20211100,20211200,20211200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de2f0>
2021-12-15 00:00:00,20211200,20220100,20220100
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddba0>
2022-01-15 00:00:00,20220100,20220200,20220200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de230>
2022-02-15 00:00:00,20220200,20220300,20220300
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddde0>
2022-03-15 00:00:00,20220300,20220400,20220400
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306dec20>
2022-04-15 00:00:00,20220400,20220500,20220500
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddff0>
2022-05-15 00:00:00,20220500,20220600,20220600
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306dece0>
2022-06-15 00:00:00,20220600,20220700,20220700
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de260>
2022-07-15 00:00:00,20220700,20220800,20220800
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddba0>
2022-08-15 00:00:00,20220800,20220900,20220900
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddea0>
2022-09-15 00:00:00,20220900,20221000,20221000
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddde0>
2022-10-15 00:00:00,20221000,20221100,20221100
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306dde70>
2022-11-15 00:00:00,20221100,20221200,20221200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddff0>
2022-12-15 00:00:00,20221200,20230100,20230100
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306deb60>
2023-01-15 00:00:00,20230100,20230200,20230200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de260>
2023-02-15 00:00:00,20230200,20230300,20230300
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de020>
2023-03-15 00:00:00,20230300,20230400,20230400
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddea0>
2023-04-15 00:00:00,20230400,20230500,20230500
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de320>
2023-05-15 00:00:00,20230500,20230600,20230600
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306dde70>
2023-06-15 00:00:00,20230600,20230700,20230700
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddf30>
2023-07-15 00:00:00,20230700,20230800,20230800
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306deb60>
2023-08-15 00:00:00,20230800,20230900,20230900
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de470>
2023-09-15 00:00:00,20230900,20231000,20231000
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de020>
2023-10-15 00:00:00,20231000,20231100,20231100
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de0e0>
2023-11-15 00:00:00,20231100,20231200,20231200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de320>
2023-12-15 00:00:00,20231200,20240100,20240100
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de2f0>
2024-01-15 00:00:00,20240100,20240200,20240200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddf30>
2024-02-15 00:00:00,20240200,20240300,20240300
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de230>
2024-03-15 00:00:00,20240300,20240400,20240400
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de470>
2024-04-15 00:00:00,20240400,20240500,20240500
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306dec20>
2024-05-15 00:00:00,20240500,20240600,20240600
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de0e0>
2024-06-15 00:00:00,20240600,20240700,20240700
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306dece0>
2024-07-15 00:00:00,20240700,20240800,20240800
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de2f0>
2024-08-15 00:00:00,20240800,20240900,20240900
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddba0>
2024-09-15 00:00:00,20240900,20241000,20241000
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de230>
2024-10-15 00:00:00,20241000,20241100,20241100
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddde0>
2024-11-15 00:00:00,20241100,20241200,20241200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306dec20>
2024-12-15 00:00:00,20241200,20250100,20250100
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddff0>
2025-01-15 00:00:00,20250100,20250200,20250200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306dece0>
2025-02-15 00:00:00,20250200,20250300,20250300
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de260>
2025-03-15 00:00:00,20250300,20250400,20250400
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddba0>
2025-04-15 00:00:00,20250400,20250500,20250500
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddea0>
2025-05-15 00:00:00,20250500,20250600,20250600
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306ddde0>
Warning! After 20250600 the next expected contract 20250700 in the held roll cycle ( FGHJKMNQUVXZ ) not available! (OK if this is at the end of the calendar)
Warning! After 20250600 the next expected contract 20250800 in the held roll cycle ( FGHJKMNQUVXZ ) not available! (OK if this is at the end of the calendar)
Warning! After 20250600 the next expected contract 20250700 in the priced roll cycle ( FGHJKMNQUVXZ ) not available! (OK if this is at the end of the calendar)
Warning! After 20250600 the next expected contract 20250800 in the priced roll cycle ( FGHJKMNQUVXZ ) not available! (OK if this is at the end of the calendar)
2025-06-15 00:00:00,20250600,20250900,20250900
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de230>
Warning! After 20250900 the next expected contract 20251000 in the held roll cycle ( FGHJKMNQUVXZ ) not available! (OK if this is at the end of the calendar)
Warning! After 20250900 the next expected contract 20251100 in the held roll cycle ( FGHJKMNQUVXZ ) not available! (OK if this is at the end of the calendar)
Warning! After 20250900 the next expected contract 20251000 in the priced roll cycle ( FGHJKMNQUVXZ ) not available! (OK if this is at the end of the calendar)
Warning! After 20250900 the next expected contract 20251100 in the priced roll cycle ( FGHJKMNQUVXZ ) not available! (OK if this is at the end of the calendar)
2025-09-15 00:00:00,20250900,20251200,20251200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x764c306de470>
Changed date from 2018-04-15 00:00:00 to 2018-04-16 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2018-04-16 05:00:00')), ('current_contract', '20180400'), ('next_contract', '20180500'), ('carry_contract', '20180500')])
Changed date from 2018-05-15 00:00:00 to 2018-05-15 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2018-05-15 05:00:00')), ('current_contract', '20180500'), ('next_contract', '20180600'), ('carry_contract', '20180600')])
Changed date from 2018-06-15 00:00:00 to 2018-06-15 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2018-06-15 05:00:00')), ('current_contract', '20180600'), ('next_contract', '20180700'), ('carry_contract', '20180700')])
Changed date from 2018-07-15 00:00:00 to 2018-07-16 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2018-07-16 05:00:00')), ('current_contract', '20180700'), ('next_contract', '20180800'), ('carry_contract', '20180800')])
Changed date from 2018-08-15 00:00:00 to 2018-08-15 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2018-08-15 05:00:00')), ('current_contract', '20180800'), ('next_contract', '20180900'), ('carry_contract', '20180900')])
Changed date from 2018-09-15 00:00:00 to 2018-09-14 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2018-09-14 05:00:00')), ('current_contract', '20180900'), ('next_contract', '20181000'), ('carry_contract', '20181000')])
Changed date from 2018-10-15 00:00:00 to 2018-10-15 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2018-10-15 05:00:00')), ('current_contract', '20181000'), ('next_contract', '20181100'), ('carry_contract', '20181100')])
Changed date from 2018-11-15 00:00:00 to 2018-11-15 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2018-11-15 06:00:00')), ('current_contract', '20181100'), ('next_contract', '20181200'), ('carry_contract', '20181200')])
Changed date from 2018-12-15 00:00:00 to 2018-12-14 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2018-12-14 06:00:00')), ('current_contract', '20181200'), ('next_contract', '20190100'), ('carry_contract', '20190100')])
Changed date from 2019-01-15 00:00:00 to 2019-01-15 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2019-01-15 06:00:00')), ('current_contract', '20190100'), ('next_contract', '20190200'), ('carry_contract', '20190200')])
Changed date from 2019-02-15 00:00:00 to 2019-02-15 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2019-02-15 06:00:00')), ('current_contract', '20190200'), ('next_contract', '20190300'), ('carry_contract', '20190300')])
Changed date from 2019-03-15 00:00:00 to 2019-03-15 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2019-03-15 05:00:00')), ('current_contract', '20190300'), ('next_contract', '20190400'), ('carry_contract', '20190400')])
Changed date from 2019-04-15 00:00:00 to 2019-04-15 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2019-04-15 05:00:00')), ('current_contract', '20190400'), ('next_contract', '20190500'), ('carry_contract', '20190500')])
Changed date from 2019-05-15 00:00:00 to 2019-05-15 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2019-05-15 05:00:00')), ('current_contract', '20190500'), ('next_contract', '20190600'), ('carry_contract', '20190600')])
Changed date from 2019-06-15 00:00:00 to 2019-06-14 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2019-06-14 05:00:00')), ('current_contract', '20190600'), ('next_contract', '20190700'), ('carry_contract', '20190700')])
Changed date from 2019-07-15 00:00:00 to 2019-07-15 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2019-07-15 05:00:00')), ('current_contract', '20190700'), ('next_contract', '20190800'), ('carry_contract', '20190800')])
Changed date from 2019-08-15 00:00:00 to 2019-08-15 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2019-08-15 05:00:00')), ('current_contract', '20190800'), ('next_contract', '20190900'), ('carry_contract', '20190900')])
Changed date from 2019-09-15 00:00:00 to 2019-09-16 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2019-09-16 05:00:00')), ('current_contract', '20190900'), ('next_contract', '20191000'), ('carry_contract', '20191000')])
Changed date from 2019-10-15 00:00:00 to 2019-10-15 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2019-10-15 05:00:00')), ('current_contract', '20191000'), ('next_contract', '20191100'), ('carry_contract', '20191100')])
Changed date from 2019-11-15 00:00:00 to 2019-11-15 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2019-11-15 06:00:00')), ('current_contract', '20191100'), ('next_contract', '20191200'), ('carry_contract', '20191200')])

                    current_contract next_contract carry_contract
current_roll_date
2018-04-16 05:00:00         20180400      20180500       20180500
2018-05-15 05:00:00         20180500      20180600       20180600
2018-06-15 05:00:00         20180600      20180700       20180700
2018-07-16 05:00:00         20180700      20180800       20180800
2018-08-15 05:00:00         20180800      20180900       20180900
...                              ...           ...            ...
2024-12-16 06:00:00         20241200      20250100       20250100
2025-01-15 06:00:00         20250100      20250200       20250200
2025-02-14 06:00:00         20250200      20250300       20250300
2025-03-14 05:00:00         20250300      20250400       20250400
2025-04-10 05:00:00         20250400      20250500       20250500

[85 rows x 3 columns]

### Create multiple prices

This section will create multiple prices. Make sure you have a reliable calendar and you have set the instrument code in the above section.

In [7]:
process_multiple_prices_single_instrument(instrument_code = instrument_code)

Getting prices to adjust roll calendar
Couldn't find matching roll date for contracts 20090900, 20091000 (even after omitting carry contracts 20091000 and 20091100)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20090900 Next: 20091000 Carry: 20091000 Next carry: 20091100)
Now trying to find suitable roll date without requiring carry contracts
Couldn't find matching roll date for contracts 20090900, 20091000 (even after omitting carry contracts 20091000 and 20091100)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't find matching roll date for contracts 20090900, 20091000 (even after omitting carry contracts 20091000 and 20091100)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't get good data for roll date 2009-09-17 23:00:00 but at start so truncating
Couldn't find matching roll date for contracts 20091000, 20091100 (even after omitting carry contracts 20091100 and 20091200)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20091000 Next: 20091100 Carry: 20091100 Next carry: 20091200)
Now trying to find suitable roll date without requiring carry contracts
Couldn't find matching roll date for contracts 20091000, 20091100 (even after omitting carry contracts 20091100 and 20091200)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't find matching roll date for contracts 20091000, 20091100 (even after omitting carry contracts 20091100 and 20091200)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't get good data for roll date 2009-10-19 23:00:00 but at start so truncating
Couldn't find matching roll date for contracts 20091100, 20091200 (even after omitting carry contracts 20091200 and 20100100)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20091100 Next: 20091200 Carry: 20091200 Next carry: 20100100)
Now trying to find suitable roll date without requiring carry contracts
Couldn't find matching roll date for contracts 20091100, 20091200 (even after omitting carry contracts 20091200 and 20100100)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't find matching roll date for contracts 20091100, 20091200 (even after omitting carry contracts 20091200 and 20100100)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't get good data for roll date 2009-11-18 23:00:00 but at start so truncating
Couldn't find matching roll date for contracts 20091200, 20100100 (even after omitting carry contracts 20100100 and 20100200)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20091200 Next: 20100100 Carry: 20100100 Next carry: 20100200)
Now trying to find suitable roll date without requiring carry contracts
Couldn't find matching roll date for contracts 20091200, 20100100 (even after omitting carry contracts 20100100 and 20100200)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't find matching roll date for contracts 20091200, 20100100 (even after omitting carry contracts 20100100 and 20100200)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't get good data for roll date 2009-12-17 23:00:00 but at start so truncating
Couldn't find matching roll date for contracts 20100100, 20100200 (even after omitting carry contracts 20100200 and 20100300)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20100100 Next: 20100200 Carry: 20100200 Next carry: 20100300)
Now trying to find suitable roll date without requiring carry contracts
Couldn't find matching roll date for contracts 20100100, 20100200 (even after omitting carry contracts 20100200 and 20100300)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't find matching roll date for contracts 20100100, 20100200 (even after omitting carry contracts 20100200 and 20100300)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't get good data for roll date 2010-01-18 23:00:00 but at start so truncating
Couldn't find matching roll date for contracts 20100200, 20100300 (even after omitting carry contracts 20100300 and 20100400)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20100200 Next: 20100300 Carry: 20100300 Next carry: 20100400)
Now trying to find suitable roll date without requiring carry contracts
Couldn't find matching roll date for contracts 20100200, 20100300 (even after omitting carry contracts 20100300 and 20100400)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't find matching roll date for contracts 20100200, 20100300 (even after omitting carry contracts 20100300 and 20100400)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't get good data for roll date 2010-02-17 23:00:00 but at start so truncating
Couldn't find matching roll date for contracts 20100300, 20100400 (even after omitting carry contracts 20100400 and 20100500)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20100300 Next: 20100400 Carry: 20100400 Next carry: 20100500)
Now trying to find suitable roll date without requiring carry contracts
Couldn't find matching roll date for contracts 20100300, 20100400 (even after omitting carry contracts 20100400 and 20100500)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't find matching roll date for contracts 20100300, 20100400 (even after omitting carry contracts 20100400 and 20100500)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't get good data for roll date 2010-03-17 23:00:00 but at start so truncating
Couldn't find matching roll date for contracts 20100400, 20100500 (even after omitting carry contracts 20100500 and 20100600)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20100400 Next: 20100500 Carry: 20100500 Next carry: 20100600)
Now trying to find suitable roll date without requiring carry contracts
Couldn't find matching roll date for contracts 20100400, 20100500 (even after omitting carry contracts 20100500 and 20100600)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't find matching roll date for contracts 20100400, 20100500 (even after omitting carry contracts 20100500 and 20100600)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't get good data for roll date 2010-04-19 23:00:00 but at start so truncating
Couldn't find matching roll date for contracts 20100500, 20100600 (even after omitting carry contracts 20100600 and 20100700)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20100500 Next: 20100600 Carry: 20100600 Next carry: 20100700)
Now trying to find suitable roll date without requiring carry contracts
Couldn't find matching roll date for contracts 20100500, 20100600 (even after omitting carry contracts 20100600 and 20100700)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't find matching roll date for contracts 20100500, 20100600 (even after omitting carry contracts 20100600 and 20100700)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't get good data for roll date 2010-05-18 23:00:00 but at start so truncating
Couldn't find matching roll date for contracts 20100600, 20100700 (even after omitting carry contracts 20100700 and 20100800)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20100600 Next: 20100700 Carry: 20100700 Next carry: 20100800)
Now trying to find suitable roll date without requiring carry contracts
Couldn't find matching roll date for contracts 20100600, 20100700 (even after omitting carry contracts 20100700 and 20100800)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't find matching roll date for contracts 20100600, 20100700 (even after omitting carry contracts 20100700 and 20100800)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't get good data for roll date 2010-06-17 23:00:00 but at start so truncating
Couldn't find matching roll date for contracts 20100700, 20100800 (even after omitting carry contracts 20100800 and 20100900)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20100700 Next: 20100800 Carry: 20100800 Next carry: 20100900)
Now trying to find suitable roll date without requiring carry contracts
Couldn't find matching roll date for contracts 20100700, 20100800 (even after omitting carry contracts 20100800 and 20100900)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't find matching roll date for contracts 20100700, 20100800 (even after omitting carry contracts 20100800 and 20100900)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't get good data for roll date 2010-07-19 23:00:00 but at start so truncating
Couldn't find matching roll date for contracts 20100800, 20100900 (even after omitting carry contracts 20100900 and 20101000)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20100800 Next: 20100900 Carry: 20100900 Next carry: 20101000)
Now trying to find suitable roll date without requiring carry contracts
Couldn't find matching roll date for contracts 20100800, 20100900 (even after omitting carry contracts 20100900 and 20101000)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't find matching roll date for contracts 20100800, 20100900 (even after omitting carry contracts 20100900 and 20101000)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't get good data for roll date 2010-08-18 23:00:00 but at start so truncating
Couldn't find matching roll date for contracts 20100900, 20101000 (even after omitting carry contracts 20101000 and 20101100)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20100900 Next: 20101000 Carry: 20101000 Next carry: 20101100)
Now trying to find suitable roll date without requiring carry contracts
Couldn't find matching roll date for contracts 20100900, 20101000 (even after omitting carry contracts 20101000 and 20101100)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't find matching roll date for contracts 20100900, 20101000 (even after omitting carry contracts 20101000 and 20101100)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't get good data for roll date 2010-09-17 23:00:00 but at start so truncating
Couldn't find matching roll date for contracts 20101000, 20101100 (even after omitting carry contracts 20101100 and 20101200)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20101000 Next: 20101100 Carry: 20101100 Next carry: 20101200)
Now trying to find suitable roll date without requiring carry contracts
Couldn't find matching roll date for contracts 20101000, 20101100 (even after omitting carry contracts 20101100 and 20101200)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't find matching roll date for contracts 20101000, 20101100 (even after omitting carry contracts 20101100 and 20101200)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't get good data for roll date 2010-10-18 23:00:00 but at start so truncating
Couldn't find matching roll date for contracts 20101100, 20101200 (even after omitting carry contracts 20101200 and 20110100)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20101100 Next: 20101200 Carry: 20101200 Next carry: 20110100)
Now trying to find suitable roll date without requiring carry contracts
Couldn't find matching roll date for contracts 20101100, 20101200 (even after omitting carry contracts 20101200 and 20110100)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't find matching roll date for contracts 20101100, 20101200 (even after omitting carry contracts 20101200 and 20110100)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't get good data for roll date 2010-11-17 23:00:00 but at start so truncating
Couldn't find matching roll date for contracts 20101200, 20110100 (even after omitting carry contracts 20110100 and 20110200)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20101200 Next: 20110100 Carry: 20110100 Next carry: 20110200)
Now trying to find suitable roll date without requiring carry contracts
Couldn't find matching roll date for contracts 20101200, 20110100 (even after omitting carry contracts 20110100 and 20110200)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't find matching roll date for contracts 20101200, 20110100 (even after omitting carry contracts 20110100 and 20110200)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't get good data for roll date 2010-12-17 23:00:00 but at start so truncating
Couldn't find matching roll date for contracts 20110100, 20110200 (even after omitting carry contracts 20110200 and 20110300)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20110100 Next: 20110200 Carry: 20110200 Next carry: 20110300)
Now trying to find suitable roll date without requiring carry contracts
Couldn't find matching roll date for contracts 20110100, 20110200 (even after omitting carry contracts 20110200 and 20110300)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't find matching roll date for contracts 20110100, 20110200 (even after omitting carry contracts 20110200 and 20110300)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't get good data for roll date 2011-01-18 23:00:00 but at start so truncating
Couldn't find matching roll date for contracts 20110200, 20110300 (even after omitting carry contracts 20110300 and 20110400)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20110200 Next: 20110300 Carry: 20110300 Next carry: 20110400)
Now trying to find suitable roll date without requiring carry contracts
Couldn't find matching roll date for contracts 20110200, 20110300 (even after omitting carry contracts 20110300 and 20110400)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't find matching roll date for contracts 20110200, 20110300 (even after omitting carry contracts 20110300 and 20110400)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't get good data for roll date 2011-02-17 23:00:00 but at start so truncating
Couldn't find matching roll date for contracts 20110300, 20110400 (even after omitting carry contracts 20110400 and 20110500)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20110300 Next: 20110400 Carry: 20110400 Next carry: 20110500)
Now trying to find suitable roll date without requiring carry contracts
Couldn't find matching roll date for contracts 20110300, 20110400 (even after omitting carry contracts 20110400 and 20110500)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't find matching roll date for contracts 20110300, 20110400 (even after omitting carry contracts 20110400 and 20110500)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't get good data for roll date 2011-03-17 23:00:00 but at start so truncating
Couldn't find matching roll date for contracts 20110400, 20110500 (even after omitting carry contracts 20110500 and 20110600)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20110400 Next: 20110500 Carry: 20110500 Next carry: 20110600)
Now trying to find suitable roll date without requiring carry contracts
Couldn't find matching roll date for contracts 20110400, 20110500 (even after omitting carry contracts 20110500 and 20110600)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't find matching roll date for contracts 20110400, 20110500 (even after omitting carry contracts 20110500 and 20110600)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't get good data for roll date 2011-04-19 23:00:00 but at start so truncating
Couldn't find matching roll date for contracts 20110500, 20110600 (even after omitting carry contracts 20110600 and 20110700)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20110500 Next: 20110600 Carry: 20110600 Next carry: 20110700)
Now trying to find suitable roll date without requiring carry contracts
Couldn't find matching roll date for contracts 20110500, 20110600 (even after omitting carry contracts 20110600 and 20110700)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't find matching roll date for contracts 20110500, 20110600 (even after omitting carry contracts 20110600 and 20110700)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Couldn't get good data for roll date 2011-05-26 07:00:00 but at start so truncating
Couldn't find matching roll date for contracts 20110600, 20110700 (even after omitting carry contracts 20110700 and 20110800)
OK if happens at the end or beginning of a roll calendar, otherwise problematic
Warning! Couldn't find matching roll date with concurrent prices for carry contracts (Current: 20110600 Next: 20110700 Carry: 20110700 Next carry: 20110800)

,PRICE,FORWARD,CARRY,PRICE_CONTRACT,FORWARD_CONTRACT,CARRY_CONTRACT
index,,,,,,
2018-04-17 05:00:00,544.75,542.9,542.9,20180500,20180600,20180600
2018-04-18 05:00:00,546.90,545.0,545.0,20180500,20180600,20180600
2018-04-19 05:00:00,544.90,543.0,543.0,20180500,20180600,20180600
2018-04-20 05:00:00,544.30,542.4,542.4,20180500,20180600,20180600
2018-04-23 05:00:00,548.70,546.8,546.8,20180500,20180600,20180600
...,...,...,...,...,...,...
2025-04-10 11:00:00,829.25,NaN,NaN,20250500,20250600,20250600
2025-04-10 12:00:00,826.40,NaN,NaN,20250500,20250600,20250600
2025-04-10 13:00:00,825.40,NaN,NaN,20250500,20250600,20250600
2025-04-10 14:00:00,821.15,NaN,NaN,20250500,20250600,20250600
2025-04-10 15:00:00,818.35,NaN,NaN,20250500,20250600,20250600

### Create adjusted prices

This will create adjusted prices from the multiple ones.

In [8]:
process_adjusted_prices_single_instrument(instrument_code = instrument_code)

index
2018-04-17 05:00:00    480.04
2018-04-18 05:00:00    482.19
2018-04-19 05:00:00    480.19
2018-04-20 05:00:00    479.59
2018-04-23 05:00:00    483.99
                        ...
2025-04-10 11:00:00    829.25
2025-04-10 12:00:00    826.40
2025-04-10 13:00:00    825.40
2025-04-10 14:00:00    821.15
2025-04-10 15:00:00    818.35
Length: 12666, dtype: float64
2025-04-10 22:39:40 DEBUG root {'component': 'parquetFuturesAdjustedPricesData', 'instrument_code': 'AEX'} Wrote 12666 lines of prices for AEX to parquetFuturesAdjustedPrices
2025-04-10 22:39:40 INFO root {'component': 'parquetFuturesAdjustedPricesData', 'instrument_code': 'AEX'} Added data for instrument AEX

index
2018-04-17 05:00:00    480.04
2018-04-18 05:00:00    482.19
2018-04-19 05:00:00    480.19
2018-04-20 05:00:00    479.59
2018-04-23 05:00:00    483.99
                        ...
2025-04-10 11:00:00    829.25
2025-04-10 12:00:00    826.40
2025-04-10 13:00:00    825.40
2025-04-10 14:00:00    821.15
2025-04-10 15:00:00    818.35
Length: 12666, dtype: float64